import sys
from Tkinter import *
import tkMessageBox
import math
import os.path
top=Tk()
top.geometry('400x300+400+300')
top.title('QUIZ WORLD')
top["bg"]="light green"
name=StringVar()
rno=StringVar()
section=StringVar()
mvar=IntVar()
var=IntVar()
var1=IntVar()
var2=IntVar()
var3=IntVar()
var4=IntVar()
var5=IntVar()
var6=IntVar()
var7=IntVar()
var8=IntVar()
var9=IntVar()
var10=IntVar()
var11=IntVar()
var12=IntVar()
var13=IntVar()
var14=IntVar()
var15=IntVar()
var16=IntVar()
var17=IntVar()
var18=IntVar()
var19=IntVar()
var20=IntVar()
var21=IntVar()
var22=IntVar()
var23=IntVar()
var24=IntVar()
var25=IntVar()
var26=IntVar()
var27=IntVar()
var28=IntVar()
var29=IntVar()
var30=IntVar()
global r1
r1=0
def record():
     x=section.get()
     y=name.get()
     z=rno.get()
     e=mvar.get()
     ch=os.path.isfile("record.txt")
     if (ch>0):
          f=open("record.txt","a")
          f.write("\n{} \t\t{}\t\t{}\t\t{}\t{}".format(x,y,z,e,r1))
          f.close()
     else:
          f=open("record.txt","w")
          f.write("SECTION \tNAME\t\tREGISTRATION NO.\tLEVEL\tMARKS\n")
          f.write("----------------------------------------------------------------------\n")
          f.write("\n{} \t\t{}\t\t{}\t\t{}\t{}".format(x,y,z,e,r1))
          f.close()
def result():
     global result
     result=Tk()
     result.geometry('400x400+400+300')
     result.title('Result')
     result["bg"]="purple"
     blank=Label(result,text=(""),bg="purple")
     blank.grid(row=1,column=0)
     res=Label(result,text=("**---------RESULT---------**"),bg="light pink")
     res.grid(row=2,column=1)
     blank1=Label(result,text=(""),bg="purple")
     blank1.grid(row=3,column=0)
     blank2=Label(result,text=(""),bg="purple")
     blank2.grid(row=4,column=0)
     r=Label(result,text=('Your Score:',r1),bg="light green",height=4,width=16,fg="brown")
     r.grid(row=5,column=1)
     blank3=Label(result,text=(""),bg="purple")
     blank3.grid(row=6,column=0)
     blank4=Label(result,text=(""),bg="purple")
     blank4.grid(row=7,column=0)
     blank6=Label(result,text=(""),bg="purple")
     blank6.grid(row=9,column=0)
     welcome()
     blank7=Label(result,text=(""),bg="purple")
     blank7.grid(row=11,column=0)
     blank8=Label(result,text=(""),bg="purple")
     blank8.grid(row=12,column=0)
     exit1=Button(result,text="EXIT",height=2,width=8,bg="sky blue",command=ex)
     exit1.grid(row=13,column=2)
     record()
def welcome():
     if (r1>=4):
          global wel
          wel=Label(result,text=("Congratulations,you have passed the test"),bg="yellow",height=3,width=36,fg="red")
          wel.grid(row=10,column=1)
     else:
          global wel1
          wel1=Label(result,text=("Sorry,you failed to clear the test"),bg="yellow",height=3,width=30,fg="red")
          wel1.grid(row=10,column=1)
def ex():
     result.destroy()
     return
def r():
     global r1
     r1=r1+1
     return r1
def nr():
     global r1
     r1=r1-0.25
     return r1
def con():
     we=tkMessageBox.askyesno(title="confirm",message="are you confirm?")
     if we > 0:
          r()
          return
def ncon():
     we=tkMessageBox.askyesno(title="confirm",message="are you confirm?")
     if we > 0:
          nr()
          return
def aend1():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top1.destroy()
          return
def aend2():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top2.destroy()
          return
def aend3():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top3.destroy()
          return
def aend4():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top4.destroy()
          return
def aend5():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top5.destroy()
          return
def aend6():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top6.destroy()
          return
def aend7():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top7.destroy()
          return
def aend8():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top8.destroy()
          return
def aend9():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top9.destroy()
          return
def aend10():
     we=tkMessageBox.askyesno(title="exit",message="are you sure?")
     if we > 0:
          top10.destroy()
          return
def alertsave():
     tkMessageBox.showinfo("Error","first complete all questions")
     return
def aeasy10():
     global top10
     top10=Tk()
     top10.geometry('400x400+400+300')
     top10.title('QUESTION BANK-EASY')
     top10["bg"]="light pink"
     blank=Label(top10,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top10,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top10,text="Ques 10:",bg="orange")
     blank1=Label(top10,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top10,text="wat is result of 'print' ??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top10,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op101=Radiobutton(top10,text="it prints 'print'",value=1,variable=var10,bg="light blue",command=ncon)
     op101.grid(row=6,column=0)
     op102=Radiobutton(top10,text="it prints blank line",value=2,variable=var10,bg="yellow",command=con)
     op102.grid(row=7,column=0)
     op103=Radiobutton(top10,text="syntex error",value=3,variable=var10,bg="green",command=ncon)
     op103.grid(row=8,column=0)
     op104=Radiobutton(top10,text="IOerror",value=4,variable=var10,bg="brown",command=ncon)
     op104.grid(row=9,column=0)
     blank3=Label(top10,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top10,text="PREV",height=2,width=8,bg="red",fg="white",command=desp10)
     pre.grid(row=11,column=0)
     sav=Button(top10,text="SAVE",height=2,width=8,bg="red",fg="white",command=sandr)
     sav.grid(row=11,column=1)
     blank4=Label(top10,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top10,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn10)
     nex.grid(row=13,column=0)
     en=Button(top10,text="END",height=2,width=8,bg="red",fg="white",command=aend10)
     en.grid(row=13,column=1)
def desn10():
     top10.destroy()
     result()
def sandr():
     top10.destroy()
     result()
def desp10():
     top10.destroy()
     aeasy9()
def aeasy9():
     global top9
     top9=Tk()
     top9.geometry('400x400+400+300')
     top9.title('QUESTION BANK-EASY')
     top9["bg"]="light pink"
     blank=Label(top9,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top9,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top9,text="Ques 9:",bg="orange")
     blank1=Label(top9,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top9,text="python is a _____",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top9,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op91=Radiobutton(top9,text="natural language",value=1,variable=var9,bg="light blue",command=ncon)
     op91.grid(row=6,column=0)
     op92=Radiobutton(top9,text="formal language",value=2,variable=var9,bg="yellow",command=con)
     op92.grid(row=7,column=0)
     op93=Radiobutton(top9,text="future language",value=3,variable=var9,bg="green",command=ncon)
     op93.grid(row=8,column=0)
     op94=Radiobutton(top9,text="astrology language",value=4,variable=var9,bg="brown",command=ncon)
     op94.grid(row=9,column=0)
     blank3=Label(top9,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top9,text="PREV",height=2,width=8,bg="red",fg="white",command=desp9)
     pre.grid(row=11,column=0)
     sav=Button(top9,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top9,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top9,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn9)
     nex.grid(row=13,column=0)
     en=Button(top9,text="END",height=2,width=8,bg="red",fg="white",command=aend9)
     en.grid(row=13,column=1)
def desn9():
     top9.destroy()
     aeasy10()
def desp9():
     top9.destroy()
     aeasy8()
def aeasy8():
     global top8
     top8=Tk()
     top8.geometry('400x400+400+300')
     top8.title('QUESTION BANK-EASY')
     top8["bg"]="light pink"
     blank=Label(top8,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top8,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top8,text="Ques 8:",bg="orange")
     blank1=Label(top8,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top8,text="how to insert comment in python??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top8,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op81=Radiobutton(top8,text="*",value=1,variable=var8,bg="light blue",command=ncon)
     op81.grid(row=6,column=0)
     op82=Radiobutton(top8,text="//",value=2,variable=var8,bg="yellow",command=ncon)
     op82.grid(row=7,column=0)
     op83=Radiobutton(top8,text="!",value=3,variable=var8,bg="green",command=ncon)
     op83.grid(row=8,column=0)
     op84=Radiobutton(top8,text="#",value=4,variable=var8,bg="brown",command=con)
     op84.grid(row=9,column=0)
     blank3=Label(top8,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top8,text="PREV",height=2,width=8,bg="red",fg="white",command=desp8)
     pre.grid(row=11,column=0)
     sav=Button(top8,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top8,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top8,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn8)
     nex.grid(row=13,column=0)
     en=Button(top8,text="END",height=2,width=8,bg="red",fg="white",command=aend8)
     en.grid(row=13,column=1)
def desn8():
     top8.destroy()
     aeasy9()
def desp8():
     top8.destroy()
     aeasy7()
def aeasy7():
     global top7
     top7=Tk()
     top7.geometry('400x400+400+300')
     top7.title('QUESTION BANK-EASY')
     top7["bg"]="light pink"
     blank=Label(top7,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top7,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top7,text="Ques 7:",bg="orange")
     blank1=Label(top7,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top7,text="wat is result of 'print 55.0%11'??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top7,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op71=Radiobutton(top7,text="5",value=1,variable=var7,bg="light blue",command=ncon)
     op71.grid(row=6,column=0)
     op72=Radiobutton(top7,text="5.0",value=2,variable=var7,bg="yellow",command=ncon)
     op72.grid(row=7,column=0)
     op73=Radiobutton(top7,text="0.0",value=3,variable=var7,bg="green",command=con)
     op73.grid(row=8,column=0)
     op74=Radiobutton(top7,text="0",value=4,variable=var7,bg="brown",command=ncon)
     op74.grid(row=9,column=0)
     blank3=Label(top7,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top7,text="PREV",height=2,width=8,bg="red",fg="white",command=desp7)
     pre.grid(row=11,column=0)
     sav=Button(top7,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top7,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top7,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn7)
     nex.grid(row=13,column=0)
     en=Button(top7,text="END",height=2,width=8,bg="red",fg="white",command=aend7)
     en.grid(row=13,column=1)
def desn7():
     top7.destroy()
     aeasy8()
def desp7():
     top7.destroy()
     aeasy6()
def aeasy6():
     global top6
     top6=Tk()
     top6.geometry('400x400+400+300')
     top6.title('QUESTION BANK-EASY')
     top6["bg"]="light pink"
     blank=Label(top6,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top6,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top6,text="Ques 6:",bg="orange")
     blank1=Label(top6,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top6,text="wat is result of 'print 55//11.0'??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top6,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op61=Radiobutton(top6,text="5",value=1,variable=var6,bg="light blue",command=ncon)
     op61.grid(row=6,column=0)
     op62=Radiobutton(top6,text="5.5",value=2,variable=var6,bg="yellow",command=ncon)
     op62.grid(row=7,column=0)
     op63=Radiobutton(top6,text="5.0",value=3,variable=var6,bg="green",command=con)
     op63.grid(row=8,column=0)
     op64=Radiobutton(top6,text="5.01",value=4,variable=var6,bg="brown",command=ncon)
     op64.grid(row=9,column=0)
     blank3=Label(top6,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top6,text="PREV",height=2,width=8,bg="red",fg="white",command=desp6)
     pre.grid(row=11,column=0)
     sav=Button(top6,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top6,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top6,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn6)
     nex.grid(row=13,column=0)
     en=Button(top6,text="END",height=2,width=8,bg="red",fg="white",command=aend6)
     en.grid(row=13,column=1)
def desn6():
     top6.destroy()
     aeasy7()
def desp6():
     top6.destroy()
     aeasy5()
def aeasy5():
     global top5
     top5=Tk()
     top5.geometry('400x400+400+300')
     top5.title('QUESTION BANK-EASY')
     top5["bg"]="light pink"
     blank=Label(top5,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top5,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top5,text="Ques 5:",bg="orange")
     blank1=Label(top5,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top5,text="wat is result of type(32)??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top5,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op51=Radiobutton(top5,text="<type 'int'>",value=1,variable=var5,bg="light blue",command=con)
     op51.grid(row=6,column=0)
     op52=Radiobutton(top5,text="<type float>",value=2,variable=var5,bg="yellow",command=ncon)
     op52.grid(row=7,column=0)
     op53=Radiobutton(top5,text="<type int>",value=3,variable=var5,bg="green",command=ncon)
     op53.grid(row=8,column=0)
     op54=Radiobutton(top5,text="<type 'str'>",value=4,variable=var5,bg="brown",command=ncon)
     op54.grid(row=9,column=0)
     blank3=Label(top5,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top5,text="PREV",height=2,width=8,bg="red",fg="white",command=desp5)
     pre.grid(row=11,column=0)
     sav=Button(top5,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top5,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top5,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn5)
     nex.grid(row=13,column=0)
     en=Button(top5,text="END",height=2,width=8,bg="red",fg="white",command=aend5)
     en.grid(row=13,column=1)
def desn5():
     top5.destroy()
     aeasy6()
def desp5():
     top5.destroy()
     aeasy4()
def aeasy4():
     global top4
     top4=Tk()
     top4.geometry('400x400+400+300')
     top4.title('QUESTION BANK-EASY')
     top4["bg"]="light pink"
     blank=Label(top4,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top4,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top4,text="Ques 4:",bg="orange")
     blank1=Label(top4,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top4,text="wat is result of type(32.4)??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top4,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op41=Radiobutton(top4,text="<type 'str'>",value=1,variable=var4,bg="sky blue",command=ncon)
     op41.grid(row=6,column=0)
     op42=Radiobutton(top4,text="<type float>",value=2,variable=var4,bg="yellow",command=ncon)
     op42.grid(row=7,column=0)
     op43=Radiobutton(top4,text="<type 'int'>",value=3,variable=var4,bg="green",command=ncon)
     op43.grid(row=8,column=0)
     op44=Radiobutton(top4,text="<type 'float'>",value=4,variable=var4,bg="brown",command=con)
     op44.grid(row=9,column=0)
     blank3=Label(top4,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top4,text="PREV",height=2,width=8,bg="red",fg="white",command=desp4)
     pre.grid(row=11,column=0)
     sav=Button(top4,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top4,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top4,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn4)
     nex.grid(row=13,column=0)
     en=Button(top4,text="END",height=2,width=8,bg="red",fg="white",command=aend4)
     en.grid(row=13,column=1)
def desn4():
     top4.destroy()
     aeasy5()
def desp4():
     top4.destroy()
     aeasy3()
def aeasy3():
     global top3
     top3=Tk()
     top3.geometry('400x400+400+300')
     top3.title('QUESTION BANK-EASY')
     top3["bg"]="light pink"
     blank=Label(top3,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top3,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top3,text="Ques 3:",bg="orange")
     blank1=Label(top3,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top3,text="wat is result of type('32')??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top3,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op31=Radiobutton(top3,text="<type 'str'>",value=1,variable=var3,bg="sky blue",command=con)
     op31.grid(row=6,column=0)
     op32=Radiobutton(top3,text="<type str>",value=2,variable=var3,bg="yellow",command=ncon)
     op32.grid(row=7,column=0)
     op33=Radiobutton(top3,text="<type 'int'>",value=3,variable=var3,bg="green",command=ncon)
     op33.grid(row=8,column=0)
     op34=Radiobutton(top3,text="<type int>",value=4,variable=var3,bg="brown",command=ncon)
     op34.grid(row=9,column=0)
     blank3=Label(top3,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top3,text="PREV",height=2,width=8,bg="red",fg="white",command=desp3)
     pre.grid(row=11,column=0)
     sav=Button(top3,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top3,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top3,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn3)
     nex.grid(row=13,column=0)
     en=Button(top3,text="END",height=2,width=8,bg="red",fg="white",command=aend3)
     en.grid(row=13,column=1)
def desn3():
     top3.destroy()
     aeasy4()
def desp3():
     top3.destroy()
     aeasy2()
def aeasy2():
     global top2
     top2=Tk()
     top2.geometry('400x400+400+300')
     top2.title('QUESTION BANK-EASY')
     top2["bg"]="light pink"
     blank=Label(top2,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top2,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top2,text="Ques 2:",bg="orange")
     blank1=Label(top2,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top2,text="How many keywords are used in Python?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top2,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op21=Radiobutton(top2,text="26",value=1,variable=var2,bg="sky blue",command=ncon)
     op21.grid(row=6,column=0)
     op22=Radiobutton(top2,text="29",value=2,variable=var2,bg="yellow",command=con)
     op22.grid(row=7,column=0)
     op23=Radiobutton(top2,text="32",value=3,variable=var2,bg="green",command=ncon)
     op23.grid(row=8,column=0)
     op24=Radiobutton(top2,text="36",value=4,variable=var2,bg="brown",command=ncon)
     op24.grid(row=9,column=0)
     blank3=Label(top2,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top2,text="PREV",height=2,width=8,bg="red",fg="white",command=desp2)
     pre.grid(row=11,column=0)
     sav=Button(top2,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top2,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top2,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn2)
     nex.grid(row=13,column=0)
     en=Button(top2,text="END",height=2,width=8,bg="red",fg="white",command=aend2)
     en.grid(row=13,column=1)
def desn2():
     top2.destroy()
     aeasy3()
def desp2():
     top2.destroy()
     aeasy1()
def aeasy1():
     global top1
     top1=Tk()
     top1.geometry('400x400+400+300')
     top1.title('QUESTION BANK-EASY')
     top1["bg"]="light pink"
     blank=Label(top1,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top1,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top1,text="Ques 1:",bg="orange")
     blank1=Label(top1,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top1,text="which of the following is not the keyword in python?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top1,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     op11=Radiobutton(top1,text="for",value=1,variable=var1,bg="sky blue",command=ncon)
     op11.grid(row=6,column=0)
     op12=Radiobutton(top1,text="and",value=2,variable=var1,bg="yellow",command=ncon)
     op12.grid(row=7,column=0)
     op13=Radiobutton(top1,text="am",value=3,variable=var1,bg="green",command=con)
     op13.grid(row=8,column=0)
     op14=Radiobutton(top1,text="def",value=4,variable=var1,bg="brown",command=ncon)
     op14.grid(row=9,column=0)
     blank3=Label(top1,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top1,text="PREV",height=2,width=8,bg="red",fg="white")
     pre.grid(row=11,column=0)
     sav=Button(top1,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top1,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     en=Button(top1,text="NEXT",height=2,width=8,bg="red",fg="white",command=desn1)
     en.grid(row=13,column=0)
     nex=Button(top1,text="END",height=2,width=8,bg="red",fg="white",command=aend1)
     nex.grid(row=13,column=1)
def desn1():
     top1.destroy()
     aeasy2()
#medium section starts
def medium10():
     global top10
     top10=Tk()
     top10.geometry('450x400+400+300')
     top10.title('QUESTION BANK-MEDIUM')
     top10["bg"]="light pink"
     blank=Label(top10,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top10,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top10,text="Ques 10:",bg="orange")
     blank1=Label(top10,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top10,text="which of the following data types is not supported in python ??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top10,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm101=Radiobutton(top10,text="Numbers",value=1,variable=var20,bg="light blue",command=ncon)
     opm101.grid(row=6,column=0)
     opm102=Radiobutton(top10,text="Strings",value=2,variable=var20,bg="yellow",command=ncon)
     opm102.grid(row=7,column=0)
     opm103=Radiobutton(top10,text="List",value=3,variable=var20,bg="green",command=ncon)
     opm103.grid(row=8,column=0)
     opm104=Radiobutton(top10,text="Slice",value=4,variable=var20,bg="brown",command=con)
     opm104.grid(row=9,column=0)
     blank3=Label(top10,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top10,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp10)
     pre.grid(row=11,column=0)
     sav=Button(top10,text="SAVE",height=2,width=8,bg="red",fg="white",command=sandr)
     sav.grid(row=11,column=1)
     blank4=Label(top10,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top10,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn10)
     nex.grid(row=13,column=0)
     en=Button(top10,text="END",height=2,width=8,bg="red",fg="white",command=aend10)
     en.grid(row=13,column=1)
def mdesn10():
     top10.destroy()
     result()
def mdesp10():
     top10.destroy()
     medium9()
def medium9():
     global top9
     top9=Tk()
     top9.geometry('450x400+400+300')
     top9.title('QUESTION BANK-MEDIUM')
     top9["bg"]="light pink"
     blank=Label(top9,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top9,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top9,text="Ques 9:",bg="orange")
     blank1=Label(top9,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top9,text="What is the output of print str[0] if str = 'Hello World!'?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top9,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm91=Radiobutton(top9,text="Hello World!",value=1,variable=var19,bg="light blue",command=ncon)
     opm91.grid(row=6,column=0)
     opm92=Radiobutton(top9,text="H",value=2,variable=var19,bg="yellow",command=con)
     opm92.grid(row=7,column=0)
     opm93=Radiobutton(top9,text="ello World!",value=3,variable=var19,bg="green",command=ncon)
     opm93.grid(row=8,column=0)
     opm94=Radiobutton(top9,text="None of the above.",value=4,variable=var19,bg="brown",command=ncon)
     opm94.grid(row=9,column=0)
     blank3=Label(top9,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top9,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp9)
     pre.grid(row=11,column=0)
     sav=Button(top9,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top9,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top9,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn9)
     nex.grid(row=13,column=0)
     en=Button(top9,text="END",height=2,width=8,bg="red",fg="white",command=aend9)
     en.grid(row=13,column=1)
def mdesn9():
     top9.destroy()
     medium10()
def mdesp9():
     top9.destroy()
     medium8()
def medium8():
     global top8
     top8=Tk()
     top8.geometry('500x400+400+300')
     top8.title('QUESTION BANK-MEDIUM')
     top8["bg"]="light pink"
     blank=Label(top8,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top8,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top8,text="Ques 8:",bg="orange")
     blank1=Label(top8,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top8,text="Which of the following function convert a string to a long in python?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top8,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm81=Radiobutton(top8,text="int(x [,base])",value=1,variable=var18,bg="light blue",command=ncon)
     opm81.grid(row=6,column=0)
     opm82=Radiobutton(top8,text=" long(x [,base] )",value=2,variable=var18,bg="yellow",command=con)
     opm82.grid(row=7,column=0)
     opm83=Radiobutton(top8,text=" float(x)",value=3,variable=var18,bg="green",command=ncon)
     opm83.grid(row=8,column=0)
     opm84=Radiobutton(top8,text=" str(x)",value=4,variable=var18,bg="brown",command=ncon)
     opm84.grid(row=9,column=0)
     blank3=Label(top8,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top8,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp8)
     pre.grid(row=11,column=0)
     sav=Button(top8,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top8,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top8,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn8)
     nex.grid(row=13,column=0)
     en=Button(top8,text="END",height=2,width=8,bg="red",fg="white",command=aend8)
     en.grid(row=13,column=1)
def mdesn8():
     top8.destroy()
     medium9()
def mdesp8():
     top8.destroy()
     medium7()
def medium7():
     global top7
     top7=Tk()
     top7.geometry('530x400+400+300')
     top7.title('QUESTION BANK-MEDIUM')
     top7["bg"]="light pink"
     blank=Label(top7,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top7,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top7,text="Ques 7:",bg="orange")
     blank1=Label(top7,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top7,text="Which of the following function convert an integer to a character in python?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top7,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm71=Radiobutton(top7,text="set(x)",value=1,variable=var17,bg="light blue",command=ncon)
     opm71.grid(row=6,column=0)
     opm72=Radiobutton(top7,text="dict(d)",value=2,variable=var17,bg="yellow",command=ncon)
     opm72.grid(row=7,column=0)
     opm73=Radiobutton(top7,text="frozenset(s)",value=3,variable=var17,bg="green",command=ncon)
     opm73.grid(row=8,column=0)
     opm74=Radiobutton(top7,text="chr(x)",value=4,variable=var17,bg="brown",command=con)
     opm74.grid(row=9,column=0)
     blank3=Label(top7,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top7,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp7)
     pre.grid(row=11,column=0)
     sav=Button(top7,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top7,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top7,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn7)
     nex.grid(row=13,column=0)
     en=Button(top7,text="END",height=2,width=8,bg="red",fg="white",command=aend7)
     en.grid(row=13,column=1)
def mdesn7():
     top7.destroy()
     medium8()
def mdesp7():
     top7.destroy()
     medium6()
def medium6():
     global top6
     top6=Tk()
     top6.geometry('600x400+400+300')
     top6.title('QUESTION BANK-MEDIUM')
     top6["bg"]="light pink"
     blank=Label(top6,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top6,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top6,text="Ques 6:",bg="orange")
     blank1=Label(top6,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top6,text="Which of the following function returns the max alphabetical character from the string str?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top6,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm61=Radiobutton(top6,text="lower()",value=1,variable=var16,bg="light blue",command=ncon)
     opm61.grid(row=6,column=0)
     opm62=Radiobutton(top6,text="Istrip()",value=2,variable=var16,bg="yellow",command=ncon)
     opm62.grid(row=7,column=0)
     opm63=Radiobutton(top6,text="max(str)",value=3,variable=var16,bg="green",command=con)
     opm63.grid(row=8,column=0)
     opm64=Radiobutton(top6,text="min(str)",value=4,variable=var16,bg="brown",command=ncon)
     opm64.grid(row=9,column=0)
     blank3=Label(top6,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top6,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp6)
     pre.grid(row=11,column=0)
     sav=Button(top6,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top6,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top6,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn6)
     nex.grid(row=13,column=0)
     en=Button(top6,text="END",height=2,width=8,bg="red",fg="white",command=aend6)
     en.grid(row=13,column=1)
def mdesn6():
     top6.destroy()
     medium7()
def mdesp6():
     top6.destroy()
     medium5()
def medium5():
     global top5
     top5=Tk()
     top5.geometry('400x400+400+300')
     top5.title('QUESTION BANK-MEDIUM')
     top5["bg"]="light pink"
     blank=Label(top5,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top5,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top5,text="Ques 5:",bg="orange")
     blank1=Label(top5,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top5,text="What is the output of len([1, 2, 3])?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top5,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm51=Radiobutton(top5,text="1",value=1,variable=var15,bg="light blue",command=ncon)
     opm51.grid(row=6,column=0)
     opm52=Radiobutton(top5,text="2",value=2,variable=var15,bg="yellow",command=ncon)
     opm52.grid(row=7,column=0)
     opm53=Radiobutton(top5,text="3",value=3,variable=var15,bg="green",command=con)
     opm53.grid(row=8,column=0)
     opm54=Radiobutton(top5,text="4",value=4,variable=var15,bg="brown",command=ncon)
     opm54.grid(row=9,column=0)
     blank3=Label(top5,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top5,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp5)
     pre.grid(row=11,column=0)
     sav=Button(top5,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top5,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top5,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn5)
     nex.grid(row=13,column=0)
     en=Button(top5,text="END",height=2,width=8,bg="red",fg="white",command=aend5)
     en.grid(row=13,column=1)
def mdesn5():
     top5.destroy()
     medium6()
def mdesp5():
     top5.destroy()
     medium4()
def medium4():
     global top4
     top4=Tk()
     top4.geometry('500x400+400+300')
     top4.title('QUESTION BANK-MEDIUM')
     top4["bg"]="light pink"
     blank=Label(top4,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top4,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top4,text="Ques 4:",bg="orange")
     blank1=Label(top4,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top4,text=" What is the output of print str * 2 if str = 'Hello World!'?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top4,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm41=Radiobutton(top4,text="Hello World!Hello World!",value=1,variable=var14,bg="light blue",command=con)
     opm41.grid(row=6,column=0)
     opm42=Radiobutton(top4,text="Hello World! * 2",value=2,variable=var14,bg="yellow",command=ncon)
     opm42.grid(row=7,column=0)
     opm43=Radiobutton(top4,text="Hello World!",value=3,variable=var14,bg="green",command=ncon)
     opm43.grid(row=8,column=0)
     opm44=Radiobutton(top4,text=" None of the above",value=4,variable=var14,bg="brown",command=ncon)
     opm44.grid(row=9,column=0)
     blank3=Label(top4,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top4,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp4)
     pre.grid(row=11,column=0)
     sav=Button(top4,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top4,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top4,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn4)
     nex.grid(row=13,column=0)
     en=Button(top4,text="END",height=2,width=8,bg="red",fg="white",command=aend4)
     en.grid(row=13,column=1)
def mdesn4():
     top4.destroy()
     medium5()
def mdesp4():
     top4.destroy()
     medium3()
def medium3():
     global top3
     top3=Tk()
     top3.geometry('600x400+400+300')
     top3.title('QUESTION BANK-MEDIUM')
     top3["bg"]="light pink"
     blank=Label(top3,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top3,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top3,text="Ques 3:",bg="orange")
     blank1=Label(top3,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top3,text="Which of the following function of dictionary gets all the values from the dictionary?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top3,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm31=Radiobutton(top3,text="getvalues()",value=1,variable=var13,bg="light blue",command=ncon)
     opm31.grid(row=6,column=0)
     opm32=Radiobutton(top3,text="value()",value=2,variable=var13,bg="yellow",command=ncon)
     opm32.grid(row=7,column=0)
     opm33=Radiobutton(top3,text="values()",value=3,variable=var13,bg="green",command=con)
     opm33.grid(row=8,column=0)
     opm34=Radiobutton(top3,text="None of the above",value=4,variable=var13,bg="brown",command=ncon)
     opm34.grid(row=9,column=0)
     blank3=Label(top3,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top3,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp3)
     pre.grid(row=11,column=0)
     sav=Button(top3,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top3,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top3,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn3)
     nex.grid(row=13,column=0)
     en=Button(top3,text="END",height=2,width=8,bg="red",fg="white",command=aend3)
     en.grid(row=13,column=1)
def mdesn3():
     top3.destroy()
     medium4()
def mdesp3():
     top3.destroy()
     medium2()
def medium2():
     global top2
     top2=Tk()
     top2.geometry('550x400+400+300')
     top2.title('QUESTION BANK-MEDIUM')
     top2["bg"]="light pink"
     blank=Label(top2,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top2,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top2,text="Ques 2:",bg="orange")
     blank1=Label(top2,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top2,text="Which of the following function changes case for all letters in string?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top2,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm11=Radiobutton(top2,text="replace(old, new [, max])",value=1,variable=var12,bg="light blue",command=ncon)
     opm11.grid(row=6,column=0)
     opm12=Radiobutton(top2,text=" strip([chars])",value=2,variable=var12,bg="yellow",command=ncon)
     opm12.grid(row=7,column=0)
     opm13=Radiobutton(top2,text="swapcase()",value=3,variable=var12,bg="green",command=con)
     opm13.grid(row=8,column=0)
     opm14=Radiobutton(top2,text="title()",value=4,variable=var12,bg="brown",command=ncon)
     opm14.grid(row=9,column=0)
     blank3=Label(top2,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top2,text="PREV",height=2,width=8,bg="red",fg="white",command=mdesp2)
     pre.grid(row=11,column=0)
     sav=Button(top2,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top2,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     en=Button(top2,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn2)
     en.grid(row=13,column=0)
     nex=Button(top2,text="END",height=2,width=8,bg="red",fg="white",command=aend2)
     nex.grid(row=13,column=1)
def mdesn2():
     top2.destroy()
     medium3()
def mdesp2():
     top2.destroy()
     medium1()
def medium1():
     global top1
     top1=Tk()
     top1.geometry('400x400+400+300')
     top1.title('QUESTION BANK-MEDIUM')
     top1["bg"]="light pink"
     blank=Label(top1,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top1,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top1,text="Ques 1:",bg="orange")
     blank1=Label(top1,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top1,text="What is the output of ['Hi!'] * 4?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top1,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     opm11=Radiobutton(top1,text=" ['Hi!', 'Hi!', 'Hi!', 'Hi!']",value=1,variable=var11,bg="light blue",command=ncon)
     opm11.grid(row=6,column=0)
     opm12=Radiobutton(top1,text=" ['Hi!'] * 4",value=2,variable=var11,bg="yellow",command=ncon)
     opm12.grid(row=7,column=0)
     opm13=Radiobutton(top1,text="Error",value=3,variable=var11,bg="green",command=con)
     opm13.grid(row=8,column=0)
     opm14=Radiobutton(top1,text="None of the above.",value=4,variable=var11,bg="brown",command=ncon)
     opm14.grid(row=9,column=0)
     blank3=Label(top1,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top1,text="PREV",height=2,width=8,bg="red",fg="white")
     pre.grid(row=11,column=0)
     sav=Button(top1,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top1,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     en=Button(top1,text="NEXT",height=2,width=8,bg="red",fg="white",command=mdesn1)
     en.grid(row=13,column=0)
     nex=Button(top1,text="END",height=2,width=8,bg="red",fg="white",command=aend1)
     nex.grid(row=13,column=1)
def mdesn1():
     top1.destroy()
     medium2()
#hard section starts
def hard10():
     global top10
     top10=Tk()
     top10.geometry('500x400+400+300')
     top10.title('QUESTION BANK-EASY')
     top10["bg"]="light pink"
     blank=Label(top10,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top10,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top10,text="Ques 10:",bg="orange")
     blank1=Label(top10,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top10,text="Which of the following function convert an integer to octal string in python?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top10,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph101=Radiobutton(top10,text="unichr(x)",value=1,variable=var30,bg="light blue",command=ncon)
     oph101.grid(row=6,column=0)
     oph102=Radiobutton(top10,text="ord(x)",value=2,variable=var30,bg="yellow",command=ncon)
     oph102.grid(row=7,column=0)
     oph103=Radiobutton(top10,text="hex(X)",value=3,variable=var30,bg="green",command=ncon)
     oph103.grid(row=8,column=0)
     oph104=Radiobutton(top10,text="oct(x)",value=4,variable=var30,bg="brown",command=con)
     oph104.grid(row=9,column=0)
     blank3=Label(top10,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top10,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp10)
     pre.grid(row=11,column=0)
     sav=Button(top10,text="SAVE",height=2,width=8,bg="red",fg="white",command=sandr)
     sav.grid(row=11,column=1)
     blank4=Label(top10,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top10,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn10)
     nex.grid(row=13,column=0)
     en=Button(top10,text="END",height=2,width=8,bg="red",fg="white",command=aend10)
     en.grid(row=13,column=1)
def hdesn10():
     top10.destroy()
     result()
def hdesp10():
     top10.destroy()
     hard9()
def hard9():
     global top9
     top9=Tk()
     top9.geometry('500x400+400+300')
     top9.title('QUESTION BANK-HARD')
     top9["bg"]="light pink"
     blank=Label(top9,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top9,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top9,text="Ques 9:",bg="orange")
     blank1=Label(top9,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top9,text="Which of the following function randomizes the items of a list in place?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top9,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph91=Radiobutton(top9,text="shuffle(lst)",value=1,variable=var29,bg="light blue",command=con)
     oph91.grid(row=6,column=0)
     oph92=Radiobutton(top9,text="capitalize()",value=2,variable=var29,bg="yellow",command=ncon)
     oph92.grid(row=7,column=0)
     oph93=Radiobutton(top9,text="isalnum()",value=3,variable=var29,bg="green",command=ncon)
     oph93.grid(row=8,column=0)
     oph94=Radiobutton(top9,text="isdigit()",value=4,variable=var29,bg="brown",command=ncon)
     oph94.grid(row=9,column=0)
     blank3=Label(top9,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top9,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp9)
     pre.grid(row=11,column=0)
     sav=Button(top9,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top9,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top9,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn9)
     nex.grid(row=13,column=0)
     en=Button(top9,text="END",height=2,width=8,bg="red",fg="white",command=aend9)
     en.grid(row=13,column=1)
def hdesn9():
     top9.destroy()
     hard10()
def hdesp9():
     top9.destroy()
     hard8()
def hard8():
     global top8
     top8=Tk()
     top8.geometry('400x400+400+300')
     top8.title('QUESTION BANK-HARD')
     top8["bg"]="light pink"
     blank=Label(top8,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top8,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top8,text="Ques 8:",bg="orange")
     blank1=Label(top8,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top8,text="What is the output of L[-2] if L = [1,2,3]?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top8,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph81=Radiobutton(top8,text="1",value=1,variable=var28,bg="light blue",command=con)
     oph81.grid(row=6,column=0)
     oph82=Radiobutton(top8,text="2",value=2,variable=var28,bg="yellow",command=ncon)
     oph82.grid(row=7,column=0)
     oph83=Radiobutton(top8,text="3",value=3,variable=var28,bg="green",command=ncon)
     oph83.grid(row=8,column=0)
     oph84=Radiobutton(top8,text=" None.",value=4,variable=var28,bg="brown",command=ncon)
     oph84.grid(row=9,column=0)
     blank3=Label(top8,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top8,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp8)
     pre.grid(row=11,column=0)
     sav=Button(top8,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top8,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top8,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn8)
     nex.grid(row=13,column=0)
     en=Button(top8,text="END",height=2,width=8,bg="red",fg="white",command=aend8)
     en.grid(row=13,column=1)
def hdesn8():
     top8.destroy()
     hard9()
def hdesp8():
     top8.destroy()
     hard7()
def hard7():
     global top7
     top7=Tk()
     top7.geometry('400x400+400+300')
     top7.title('QUESTION BANK-HARD')
     top7["bg"]="light pink"
     blank=Label(top7,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top7,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top7,text="Ques 7:",bg="orange")
     blank1=Label(top7,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top7,text="wat is result of 'print 55.0%11'??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top7,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph71=Radiobutton(top7,text="5",value=1,variable=var27,bg="light blue",command=ncon)
     oph71.grid(row=6,column=0)
     oph72=Radiobutton(top7,text="5.0",value=2,variable=var27,bg="yellow",command=ncon)
     oph72.grid(row=7,column=0)
     oph73=Radiobutton(top7,text="0.0",value=3,variable=var27,bg="green",command=con)
     oph73.grid(row=8,column=0)
     oph74=Radiobutton(top7,text="0",value=4,variable=var27,bg="brown",command=ncon)
     oph74.grid(row=9,column=0)
     blank3=Label(top7,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top7,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp7)
     pre.grid(row=11,column=0)
     sav=Button(top7,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top7,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top7,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn7)
     nex.grid(row=13,column=0)
     en=Button(top7,text="END",height=2,width=8,bg="red",fg="white",command=aend7)
     en.grid(row=13,column=1)
def hdesn7():
     top7.destroy()
     hard8()
def hdesp7():
     top7.destroy()
     hard6()
def hard6():
     global top6
     top6=Tk()
     top6.geometry('400x400+400+300')
     top6.title('QUESTION BANK-HARD')
     top6["bg"]="light pink"
     blank=Label(top6,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top6,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top6,text="Ques 6:",bg="orange")
     blank1=Label(top6,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top6,text="wat is result of 'print 55//11.0'??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top6,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph61=Radiobutton(top6,text="5",value=1,variable=var26,bg="light blue",command=ncon)
     oph61.grid(row=6,column=0)
     oph62=Radiobutton(top6,text="5.5",value=2,variable=var26,bg="yellow",command=ncon)
     oph62.grid(row=7,column=0)
     oph63=Radiobutton(top6,text="5.0",value=3,variable=var26,bg="green",command=con)
     oph63.grid(row=8,column=0)
     oph64=Radiobutton(top6,text="5.01",value=4,variable=var26,bg="brown",command=ncon)
     oph64.grid(row=9,column=0)
     blank3=Label(top6,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top6,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp6)
     pre.grid(row=11,column=0)
     sav=Button(top6,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top6,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top6,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn6)
     nex.grid(row=13,column=0)
     en=Button(top6,text="END",height=2,width=8,bg="red",fg="white",command=aend6)
     en.grid(row=13,column=1)
def hdesn6():
     top6.destroy()
     hard7()
def hdesp6():
     top6.destroy()
     hard5()
def hard5():
     global top5
     top5=Tk()
     top5.geometry('500x400+400+300')
     top5.title('QUESTION BANK-HARD')
     top5["bg"]="light pink"
     blank=Label(top5,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top5,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top5,text="Ques 5:",bg="orange")
     blank1=Label(top5,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top5,text="What is the following function removes last object from a list?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top5,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph51=Radiobutton(top5,text=" list.index(obj)",value=1,variable=var25,bg="light blue",command=ncon)
     oph51.grid(row=6,column=0)
     oph52=Radiobutton(top5,text=" list.insert(index, obj)",value=2,variable=var25,bg="yellow",command=ncon)
     oph52.grid(row=7,column=0)
     oph53=Radiobutton(top5,text="list.pop(obj=list[-1])",value=3,variable=var25,bg="green",command=con)
     oph53.grid(row=8,column=0)
     oph54=Radiobutton(top5,text=" list.remove(obj)",value=4,variable=var25,bg="brown",command=ncon)
     oph54.grid(row=9,column=0)
     blank3=Label(top5,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top5,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp5)
     pre.grid(row=11,column=0)
     sav=Button(top5,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top5,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top5,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn5)
     nex.grid(row=13,column=0)
     en=Button(top5,text="END",height=2,width=8,bg="red",fg="white",command=aend5)
     en.grid(row=13,column=1)
def hdesn5():
     top5.destroy()
     hard6()
def hdesp5():
     top5.destroy()
     hard4()
def hard4():
     global top4
     top4=Tk()
     top4.geometry('400x400+400+300')
     top4.title('QUESTION BANK-HARD')
     top4["bg"]="light pink"
     blank=Label(top4,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top4,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top4,text="Ques 4:",bg="orange")
     blank1=Label(top4,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top4,text="wat is result of type(32.4)??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top4,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph41=Radiobutton(top4,text="<type 'str'>",value=1,variable=var24,bg="light blue",command=ncon)
     oph41.grid(row=6,column=0)
     oph42=Radiobutton(top4,text="<type float>",value=2,variable=var24,bg="yellow",command=ncon)
     oph42.grid(row=7,column=0)
     oph43=Radiobutton(top4,text="<type 'int'>",value=3,variable=var24,bg="green",command=ncon)
     oph43.grid(row=8,column=0)
     oph44=Radiobutton(top4,text="<type 'float'>",value=4,variable=var24,bg="brown",command=con)
     oph44.grid(row=9,column=0)
     blank3=Label(top4,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top4,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp4)
     pre.grid(row=11,column=0)
     sav=Button(top4,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top4,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top4,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn4)
     nex.grid(row=13,column=0)
     en=Button(top4,text="END",height=2,width=8,bg="red",fg="white",command=aend4)
     en.grid(row=13,column=1)
def hdesn4():
     top4.destroy()
     hard5()
def hdesp4():
     top4.destroy()
     hard3()
def hard3():
     global top3
     top3=Tk()
     top3.geometry('400x400+400+300')
     top3.title('QUESTION BANK-HARD')
     top3["bg"]="light pink"
     blank=Label(top3,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top3,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top3,text="Ques 3:",bg="orange")
     blank1=Label(top3,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top3,text="wat is result of type('32')??",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top3,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph31=Radiobutton(top3,text="<type 'str'>",value=1,variable=var23,bg="light blue",command=con)
     oph31.grid(row=6,column=0)
     oph32=Radiobutton(top3,text="<type str>",value=2,variable=var23,bg="yellow",command=ncon)
     oph32.grid(row=7,column=0)
     oph33=Radiobutton(top3,text="<type 'int'>",value=3,variable=var23,bg="green",command=ncon)
     oph33.grid(row=8,column=0)
     oph34=Radiobutton(top3,text="<type int>",value=4,variable=var23,bg="brown",command=ncon)
     oph34.grid(row=9,column=0)
     blank3=Label(top3,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top3,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp3)
     pre.grid(row=11,column=0)
     sav=Button(top3,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top3,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top3,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn3)
     nex.grid(row=13,column=0)
     en=Button(top3,text="END",height=2,width=8,bg="red",fg="white",command=aend3)
     en.grid(row=13,column=1)
def hdesn3():
     top3.destroy()
     hard4()
def hdesp3():
     top3.destroy()
     hard2()
def hard2():
     global top2
     top2=Tk()
     top2.geometry('500x400+400+300')
     top2.title('QUESTION BANK-HARD')
     top2["bg"]="light pink"
     blank=Label(top2,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top2,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top2,text="Ques 2:",bg="orange")
     blank1=Label(top2,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top2,text="Which of the following function gets the length of the string?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top2,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph21=Radiobutton(top2,text="issupper()",value=1,variable=var22,bg="light blue",command=ncon)
     oph21.grid(row=6,column=0)
     oph22=Radiobutton(top2,text="join(seq)",value=2,variable=var22,bg="yellow",command=ncon)
     oph22.grid(row=7,column=0)
     oph23=Radiobutton(top2,text="len(string)",value=3,variable=var22,bg="green",command=con)
     oph23.grid(row=8,column=0)
     oph24=Radiobutton(top2,text="ljust(width[,fillchar])",value=4,variable=var22,bg="brown",command=ncon)
     oph24.grid(row=9,column=0)
     blank3=Label(top2,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top2,text="PREV",height=2,width=8,bg="red",fg="white",command=hdesp2)
     pre.grid(row=11,column=0)
     sav=Button(top2,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top2,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     nex=Button(top2,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn2)
     nex.grid(row=13,column=0)
     en=Button(top2,text="END",height=2,width=8,bg="red",fg="white",command=aend2)
     en.grid(row=13,column=1)
def hdesn2():
     top2.destroy()
     hard3()
def hdesp2():
     top2.destroy()
     hard1()
def hard1():
     global top1
     top1=Tk()
     top1.geometry('400x400+400+300')
     top1.title('QUESTION BANK-HARD')
     top1["bg"]="light pink"
     blank=Label(top1,text=(""),bg="light pink")
     blank.grid(row=1,column=0)
     res=name.get()
     show=Label(top1,text=("HeLLo",res),bg="light green")
     show.grid(row=2,column=0)
     q1=Label(top1,text="Ques 1:",bg="orange")
     blank1=Label(top1,text=(""),bg="light pink")
     blank1.grid(row=3,column=0)
     q1.grid(row=4,column=0)
     qu1=Label(top1,text="What is the output of for x in [1, 2, 3]: print x?",bg="orange")
     qu1.grid(row=4,column=1)
     blank2=Label(top1,text=(""),bg="light pink")
     blank2.grid(row=5,column=0)
     oph11=Radiobutton(top1,text="x x x",value=1,variable=var21,bg="light blue",command=ncon)
     oph11.grid(row=6,column=0)
     oph12=Radiobutton(top1,text="1 2 3",value=2,variable=var21,bg="yellow",command=con)
     oph12.grid(row=7,column=0)
     oph13=Radiobutton(top1,text="Error",value=3,variable=var21,bg="green",command=ncon)
     oph13.grid(row=8,column=0)
     oph14=Radiobutton(top1,text="None.",value=4,variable=var21,bg="brown",command=ncon)
     oph14.grid(row=9,column=0)
     blank3=Label(top1,text=(""),bg="light pink")
     blank3.grid(row=10,column=0)
     pre=Button(top1,text="PREV",height=2,width=8,bg="red",fg="white")
     pre.grid(row=11,column=0)
     sav=Button(top1,text="SAVE",height=2,width=8,bg="red",fg="white",command=alertsave)
     sav.grid(row=11,column=1)
     blank4=Label(top1,text=(""),bg="light pink")
     blank4.grid(row=12,column=0)
     en=Button(top1,text="NEXT",height=2,width=8,bg="red",fg="white",command=hdesn1)
     en.grid(row=13,column=0)
     nex=Button(top1,text="END",height=2,width=8,bg="red",fg="white",command=aend1)
     nex.grid(row=13,column=1)
def hdesn1():
     top1.destroy()
     hard2()
def reasy():
     B=Button(top,text="SUBMIT",height=2,width=6,bg="green",fg="blue",command=calleasy)
     B.grid(row=9,column=2)
def calleasy():
     top.destroy()
     aeasy1()
def rmed():
     B=Button(top,text="SUBMIT",height=2,width=6,bg="green",fg="blue",command=callmedium)
     B.grid(row=9,column=2)
def callmedium():
     top.destroy()
     medium1()
def rhard():
     B=Button(top,text="SUBMIT",height=2,width=6,bg="green",fg="blue",command=callhard)
     B.grid(row=9,column=2)
def callhard():
     top.destroy()
     hard1()
l1=Label(top,text="WELCOME IN QUIZ WORLD       ",bg="black",fg="white")
l1.grid(row=1,column=0)
L2=Label(top,text="Name:",bg="pink",fg="blue")
L2.grid(row=2,column=0)
E1=Entry(top,bd=5,textvariable=name,fg="blue")
E1.grid(row=2, column=1)
L3=Label(top,text="Registration No.:",bg="pink",fg="blue") 
L3.grid(row=3, column=0)
E2=Entry(top,bd=5,textvariable=rno,fg="blue")
E2.grid(row=3, column=1)
L4=Label(top,text="Section:",bg="pink",fg="blue")
L4.grid(row=4,column=0)
E3=Entry(top,bd=5,textvariable=section,fg="blue")
E3.grid(row=4, column=1)
L5=Label(top,text="Level",bg="pink",fg="blue")
L5.grid(row=5,column=0)
easy=Radiobutton(top,text="Easy",value=1,variable=mvar,bg="yellow",fg="red",command=reasy)
easy.grid(row=5,column=1)
moderate=Radiobutton(top,text="Medium",value=2,variable=mvar,bg="yellow",fg="red",command=rmed)
moderate.grid(row=6,column=1)
hard=Radiobutton(top,text="Hard",value=3,variable=mvar,bg="yellow",fg="red",command=rhard)
hard.grid(row=7,column=1)
mainloop()
